version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/ContosoTraders.Ui.Website" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
